### ISSUE TITLE
No 2FA prompt

### ISSUE THREAD

**Issue by Cytreen** [Foxlider/Fox-s-Arma-Server-Tool-Extended-Rewrite#10]
This runs into the same old issue of FAST ware the program does not pop up the screen to enter 2FA keys if a steam account has 2FA enabled.

**Comment by Foxlider** [comment]
Cause : 
 - FASTER could not get the line of text from steamcmd's output asking for SteamGuard token. 

Workaround : 
You can try to login via the steamcmd console directly and your credentials should be saved. 
This issue is being worked on.
