### ISSUE TITLE
[BUG] Will not launch

### ISSUE THREAD

**Issue by lividsubset3** [Foxlider/Fox-s-Arma-Server-Tool-Extended-Rewrite#101]
**Describe the bug**
Just will not launch

**To Reproduce**
Just wont launch

**Expected behaviour**
Launch

**Actual behaviour**
double click prompt to open as admin, click yes, does not open

**OS Version (required):**
 - OS: Windows 10 2004
 - Version 1.6b

**Comment by Foxlider** [comment]
From FASTER's Discord FAQ channel : 

> 
> 3. FASTER does not start anymore / keeps crashing !
> Check in your logs if you are having issues about missing DLLs. 
> The message should look like the following : 
> System.IO.FileNotFoundException: Could not load file or assembly 'System.Something.I.Gess, Version=4.0.0.0, Culture=neutral, PublicKeyToken=blahblahblah'. The system cannot find the file specified.
> This is a known bug. FASTER files are extracted in the temp folder while running and windows likes to "clean" this folder. Current workaround is to set the DOTNET_BUNDLE_EXTRACT_BASE_DIR environment variable to some path such as C:\Users\your_user_name\Documents\Apps\FASTER. It should prevent Windows from deleting the files.
