### ISSUE TITLE
[BUG] ERROR! Timeout downloading item 583496184

### ISSUE THREAD

**Issue by Patron54** [Foxlider/Fox-s-Arma-Server-Tool-Extended-Rewrite#102]
**Describe the bug**
Trying to download CUP Terrain Core, it loading and after gives an error "ERROR! Timeout downloading item 583496184"

**To Reproduce**
Steps to reproduce the behaviour:
1. Add Steam mod with ID 583496184
2. Click on Update
3. It will load for a long time.

**Expected behaviour**
Mod downloads and it status is Up to date

**Actual behaviour**
Mod is not downloads and it status is Download Not Complete

**Screenshots**
![image](https://user-images.githubusercontent.com/6143623/89935938-acd3a280-dc1b-11ea-98c6-31579ddbb9d1.png)

**OS Version (required):**
 - OS: Windows Server 2019 ver 1809
 - Build 17763.316

**FASTER Version:**
 - Version 1.6b

**Additional context**
Found something like solution on Steam Discussion but not sure how to use it with the FASTER [Link to Steam Discussion](https://steamcommunity.com/discussions/forum/1/215439774859993377/)

**Comment by Foxlider** [comment]
Fixed in 1.7a
