### ISSUE TITLE
Fast closes when you try to set it on a user

### ISSUE THREAD

**Issue by diaverso** [Foxlider/Fox-s-Arma-Server-Tool-Extended-Rewrite#104]
**Describe the bug**
Error opening faster on a user.
When you open faster with a user, and you try to configure it, it closes suddenly

**To Reproduce**
Steps to reproduce the behaviour:
1. Start Faster
2. Steam updater
3. Install directory
4. Crash

**Expected behaviour**
That there will be the directory to be able to select the installation path

**Actual behaviour**
Closes for no reason

**Screenshots**
Video Link
https://www.youtube.com/watch?v=CScI_XwLiD4

**OS Version (required):**
 - OS: Windows 2019 Server
 - Version 1.6.2.0

**Additional context**
The weird thing, is that in one user if he lets me open it and configure it, but in the second one

**Comment by Foxlider** [comment]
Make sure you open FASTER with Administrator Perms
Also, if you could send some logs, maybe that could help. 
Logs are available in the Windows Event Viewer

**Comment by diaverso** [comment]
> 
> 
> Make sure you open FASTER with Administrator Perms
> Also, if you could send some logs, maybe that could help.
> Logs are available in the Windows Event Viewer

Aplication Error: https://gist.github.com/diaverso/45eaf055720f4c50caadea4c4fa48f72
.Net Runtime: https://gist.github.com/diaverso/2e5c0746a58e02f5239c4c97c7f03a9a
Sorry, I'm Spanish and I have it in Spanish

**Comment by Foxlider** [comment]
So it seems that your user settings for 1.6.2 are corrupted. 
The app tried to read a parameter and failed and caused a crash

**Comment by diaverso** [comment]
Hello, sorry for not responding at this time.
In the end reinstall the operating system to fix it.
But it happened to me again

First error that gave:
https://gist.github.com/diaverso/9512a592921b0c79f505c84003866022
Aplication Error:
https://gist.github.com/diaverso/85960698254de1e8967e74fc3d3e1684
Windows error Reporting:
https://gist.github.com/diaverso/67730e261460b6a9cf424d54be6a8f97

Clear the data from AppData \ Local \ FoxliCorp \ FASTER_StrongName_r3kmcr0zqf35dnhwrlga5cvn2azjfziz \ 1.6.2.0

You give it to start and it comes out to put the data, but when you give it to explore the files directory it closes

Now give other errors
.Net Runtime:
https://gist.github.com/diaverso/e35b080535de2802fe0ed17c1bc576c0
I don't understand why this happens.
