### ISSUE TITLE
Steam CMD Output update

### ISSUE THREAD

**Issue by Cytreen** [Foxlider/Fox-s-Arma-Server-Tool-Extended-Rewrite#13]
Make steam CMD output window on the steam Updater form, output as updates are occurring. Also should allow for scrolling the output once updates are complete. This will allow server operators to see what's going on during the programs operation as some mods on workshop will give output errors as unreachable or failed to download.

Would be nice to see this at some point.

**Comment by Foxlider** [comment]
Because of how steamcmd is made it is quite hard to do so. I can add the scroll on the textbox but the output written is already displaying as fast and soon as possible. 
I might be able to add some text to show more precisely what action the program is starting.

**Comment by Cytreen** [comment]
being able to scroll back through whats outputted would be great, otherwise users will never know what the steamCMD output errors are if one occures
