### ISSUE TITLE
config.cfg not being correctly built from FASTER settings

### ISSUE THREAD

**Issue by Cytreen** [Foxlider/Fox-s-Arma-Server-Tool-Extended-Rewrite#14]
in the server config.cfg
Class missions is missing all entries
config.cfg also has errors
current FASTER config.cfg errors
config.cfg contains
maxPlayers = "32";

correct entry for this setting is not a string
needs to be
maxPlayers = 32;
i can confirm that none of the mission settings or difficulty settings are being set
current
class Missions {
};

needs to be
class Missions {
    class Mission_1 {
        template = "mission.Altis";
        difficulty = "Custom";
    };
};

**Comment by Foxlider** [comment]
The config part is by far the hardest to convert from old VB.NET to C# and I forgot a lot of things. Thanks for reporting this
