### ISSUE TITLE
[FEATURE] Confirmation prompt when deleting the server profile

### ISSUE THREAD

**Issue by corp-0** [Foxlider/Fox-s-Arma-Server-Tool-Extended-Rewrite#19]
**Is your feature request related to a problem? Please describe.**
I have clicked on the delete server profile button more times than what I'd like to admit. It is way too harmful to don't ask back to the user if they are sure they want to delete the profile.

**Describe the solution you'd like**
A pop up window with the typical "Are you sure you want to delete this profile? [yes/no].

**Additional context**
![image](https://user-images.githubusercontent.com/43683714/62310437-894a1980-b457-11e9-9f3e-c0f0c1b0971b.png)

**Comment by Foxlider** [comment]
Didn't thought about it... Why didn't I thought about it ?
