### ISSUE TITLE
[FEATURE] Add network setting option presets

### ISSUE THREAD

**Issue by QuickCentralHosting** [Foxlider/Fox-s-Arma-Server-Tool-Extended-Rewrite#20]
**Is your feature request related to a problem? Please describe.**
I know tons of people who have issues with Arma 3 networking and was hoping this could be an added feature. If they person using it knows their download and upload speed they could enter it and the program optimized the services to run smoother for them because we all know Arma 3 is garbage with default network settings.

**Describe the solution you'd like**
An input area that gives people the ability to take their download and upload speed, enter it into the program and it can set the network settings to better work with their speeds. Probably to make it easy, put it in ranges. So downloads from 0Mbps to 50Mbps get specific settings, then 50-150Mbps get better settings, and anything above 150Mbps to 40Gbps get very optimized settings to get the most usage of their network.

**Describe alternatives you've considered**
I mean the alternative is testing forever, waiting for arma 3 to launch, not work and then spend maybe days trying stuff to make it work. This would be the best option.

**Additional context**
N/A

**Comment by Foxlider** [comment]
This issue is for advanced users only. I event don't fiddle with performance settings and I expect people fiddling with those to know exactly what they are doing. Making it easier might cause less experienced users to encounter issues or set up things the wrong way.
