### ISSUE TITLE
[BUG] FASTER insists that Workshop mod is from another game and refuses to add it to list of steam mods

### ISSUE THREAD

**Issue by Drift91** [Foxlider/Fox-s-Arma-Server-Tool-Extended-Rewrite#21]
**Describe the bug**
For some reason it says that the following mod is from another game and refuses to add it:
https://steamcommunity.com/sharedfiles/filedetails/?id=286579896

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to steam mods.
2. Click 'add steam mod'.
3. Enter the following: https://steamcommunity.com/sharedfiles/filedetails/?id=286579896

**Expected behaviour**
The mod should be added to the list.

**Actual behaviour**
I get an error claiming the mod is for another game.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/2638764/62408911-a6890000-b59d-11e9-93cc-61f59d331a93.png)

**OS Version (required):**
 - OS: Windows Server 2016 (1607)
 - Version 1.2d

**Additional context**
May be caused by the fact that the mod has a DLC as a prerequisite.

**Comment by Foxlider** [comment]
The mod's Steam AppID is not Arma 3 (107410) but Arma 3 Tools (233800) and is not fully compatible with Arma 3. You can still force it by installing it in Local Mods

**Comment by Otarius-big** [comment]
![Безымянный](https://user-images.githubusercontent.com/36573405/63636582-43f9c000-c682-11e9-90e7-776ae5daaff2.jpg)

**Comment by Otarius-big** [comment]
imported mod list from arma3 launcher

**Comment by Foxlider** [comment]
Can you please send me the last FASTER logs from the event viewer ?
![image](https://user-images.githubusercontent.com/19773387/63638014-70faa280-c683-11e9-86c1-db17b4dc46df.png)

**Comment by Otarius-big** [comment]
ok  where can i find it?

сб, 24 авг. 2019 г., 17:25 Keelah <notifications@github.com>:

**Comment by Foxlider** [comment]
Windows -> Event Logs -> Windows Logs -> Application and search for errors with FASTER somewhere

**Comment by Otarius-big** [comment]
Starting SteamCMD to update Addon
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.
Logging in user 'otarius23' to Steam Public ...

Logged in OK
Waiting for user info...OK
Downloading item 463939057 ...

Success. Downloaded item 463939057 to "E:\Program Files (x86)\SteamCMD\steamapps\workshop\content\107410\463939057" (152751659 bytes) Downloading item 773131200 ...

Success. Downloaded item 773131200 to "E:\Program Files (x86)\SteamCMD\steamapps\workshop\content\107410\773131200" (42722 bytes) Downloading item 773125288 ...

Success. Downloaded item 773125288 to "E:\Program Files (x86)\SteamCMD\steamapps\workshop\content\107410\773125288" (82773 bytes) Downloading item 884966711 ...

Success. Downloaded item 884966711 to "E:\Program Files (x86)\SteamCMD\steamapps\workshop\content\107410\884966711" (8885 bytes) Downloading item 450814997 ...

Success. Downloaded item 450814997 to "E:\Program Files (x86)\SteamCMD\steamapps\workshop\content\107410\450814997" (2652787 bytes) Downloading item 1809837151 ...

Success. Downloaded item 1809837151 to "E:\Program Files (x86)\SteamCMD\steamapps\workshop\content\107410\1809837151" (361140 bytes) Downloading item 1826223998 ...

Success. Downloaded item 1826223998 to "E:\Program Files (x86)\SteamCMD\steamapps\workshop\content\107410\1826223998" (162610 bytes) Downloading item 1375890861 ...

Success. Downloaded item 1375890861 to "E:\Program Files (x86)\SteamCMD\steamapps\workshop\content\107410\1375890861" (364255 bytes) Downloading item 583496184 ...

ERROR! Download item 583496184 failed (Request has been canceled).Downloading item 583544987 ...

Success. Downloaded item 583544987 to "E:\Program Files (x86)\SteamCMD\steamapps\workshop\content\107410\583544987" (3419057156 bytes) Downloading item 825181638 ...

Success. Downloaded item 825181638 to "E:\Program Files (x86)\SteamCMD\steamapps\workshop\content\107410\825181638" (871127288 bytes) Downloading item 333310405 ...

Success. Downloaded item 333310405 to "E:\Program Files (x86)\SteamCMD\steamapps\workshop\content\107410\333310405" (628454 bytes) Downloading item 825179978 ...

Success. Downloaded item 825179978 to "E:\Program Files (x86)\SteamCMD\steamapps\workshop\content\107410\825179978" (107575253 bytes) Downloading item 648172507 ...

Success. Downloaded item 648172507 to "E:\Program Files (x86)\SteamCMD\steamapps\workshop\content\107410\648172507" (397922929 bytes) Downloading item 861133494 ...

Success. Downloaded item 861133494 to "E:\Program Files (x86)\SteamCMD\steamapps\workshop\content\107410\861133494" (1437729541 bytes) Downloading item 1429098683 ...

Success. Downloaded item 1429098683 to "E:\Program Files (x86)\SteamCMD\steamapps\workshop\content\107410\1429098683" (68656 bytes) Downloading item 945476727 ...

Success. Downloaded item 945476727 to "E:\Program Files (x86)\SteamCMD\steamapps\workshop\content\107410\945476727" (55095 bytes) Downloading item 1180534892 ...

Success. Downloaded item 1180534892 to "E:\Program Files (x86)\SteamCMD\steamapps\workshop\content\107410\1180534892" (50643 bytes) Downloading item 1486541773 ...

Success. Downloaded item 1486541773 to "E:\Program Files (x86)\SteamCMD\steamapps\workshop\content\107410\1486541773" (41986 bytes) Downloading item 1180533757 ...

Success. Downloaded item 1180533757 to "E:\Program Files (x86)\SteamCMD\steamapps\workshop\content\107410\1180533757" (56322 bytes) Downloading item 735566597 ...

Success. Downloaded item 735566597 to "E:\Program Files (x86)\SteamCMD\steamapps\workshop\content\107410\735566597" (1789845258 bytes) Downloading item 843425103 ...ERROR! Timeout downloading item 843425103\src\clientdll\depotreconstruct.cpp (1348) : Assertion Failed: m_nOutstandingWorkItems == 0
CWorkThreadPool::~CWorkThreadPool: work complete queue not empty, 3 items discarded.
CWorkThreadPool::~CWorkThreadPool: work complete queue not empty, 2 items discarded.
Redirecting stderr to 'E:\Program Files (x86)\SteamCMD\logs\stderr.txt'
[  0%] РџСЂРѕРІРµСЂРєР° РЅР° РЅР°Р»РёС‡РёРµ РѕР±РЅРѕРІР»РµРЅРёР№...

[----] РџСЂРѕРІРµСЂРєР° СѓСЃС‚Р°РЅРѕРІРєРё...

SteamCMD Exited

**Comment by Foxlider** [comment]
This seems to be a connexion issue not related with the initial issue.

**Comment by Foxlider** [comment]
Will reopen issue when more information is received from users
