### ISSUE TITLE
[BUG] FASTER able to run as non-administrator, which breaks symbolic link function for steam mods

### ISSUE THREAD

**Issue by Drift91** [Foxlider/Fox-s-Arma-Server-Tool-Extended-Rewrite#22]
**Describe the bug**
FASTER does not force an adminstrator UAC prompt at launch, resulting in no symlinks being made for the steam mods when they download, unless manually run as administrator.

**To Reproduce**
Steps to reproduce the behaviour:
1. Double-click the program executable or shortcut.
2. Import and download steam mods.
3. Go to server profile and refresh the mods list.
4. None of them show up due to lack of symbolic links in Arma folder.

**Expected behaviour**
FASTER brings up UAC elevation prompt and symlinks are created while mods download resulting in the mods showing up in the server profile mod list.

**Actual behaviour**
Symlinks aren't created and mods don't show up in server profile mods list.

**Screenshots**
N/A

**OS Version (required):**
 - OS: Windows Server 2016 (1607)
 - Version 1.2d

**Additional context**
An alternative to forcing a UAC prompt, if it requires some sort of certificate from Microsoft or similar approval, would be to give a popup message on non-elevated launch warning that manually launching as admin or setting to run as admin in compatibility settings is necessary for proper steam mod installation.

**Comment by Foxlider** [comment]
After checking, Windows does not require admin privileges for symlinks to work. If it does not work on your system, manually run FASTER as administrator on launch

**Comment by alec-hs** [comment]
Windows by deafult requires a user to be in the Administrators group to create Symlinks - this is shown below in Security Policy (same on Win10, Server 2016, 2019 etc).

![image](https://user-images.githubusercontent.com/6503411/63592819-7506c180-c5aa-11e9-810a-9c56b7b81ac1.png)

**Comment by Foxlider** [comment]
Oh right... I might need to check this at launch then.

**Comment by alexbobp** [comment]
I experienced this issue.  I tried both updating the above mentioned security policy, as well as running FASTER as admin, but I can't seem to figure out how to get it to re-attempt creating those symlinks for already downloaded mods.  Any workaround?

**Comment by Foxlider** [comment]
You can use the command `mklink /D "destinationPath" "originPath"`

**Comment by Foxlider** [comment]
It should be fixed in the next version of FASTER though.

**Comment by Foxlider** [comment]
Fixed in #36
