### ISSUE TITLE
[BUG] Checking for steam mod updates results in numerous "Cannot reach steam API" errors. Possibly being rate limited by steam servers?

### ISSUE THREAD

**Issue by Drift91** [Foxlider/Fox-s-Arma-Server-Tool-Extended-Rewrite#23]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Make large mod preset with Arma 3 launcher containing 100+ mods.
2. Import the mods. (will likely throw same error)
3. Check for updates. Will most likely throw the error.

**Expected behaviour**
All the mods to be imported and/or checked without API connection problems.

**Actual behaviour**
A random amount of mods will throw the API error, sometimes back-to-back.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/2638764/62414529-bbd84b80-b5ea-11e9-95cf-75caff59b716.png)

**OS Version (required):**
 - OS: Windows Server 2016 (1607)
 - Version [1.2d]

**Additional context**
I know most people don't have as many mods in their preset and it may seem like that's the issue. However it sometimes errors right away, implying that it has nothing to do with mod quantity. I suspect that the rate at which mods are checked might need to be reduced due to Steam's servers regularly being overloaded.

I should also note that while I've only experienced this for the past few hours with FASTER, FAST2 did regularly crash due to the Steam API problem for the past month or two I've been using it. so I'm pretty sure it's not just a temporary overload of the Steam API and is an actual problem with FAST2/FASTER making requests too quickly.

**Comment by Foxlider** [comment]
This might be linked to your account. Rate limits is probably thrown because of the amount of request you do to steam API on one single account. I had this issue with some games as well when I had too many mods. I'd advise updating the mods one by one. 

In the meantime, I will try to get more information about this issue.

**Comment by Foxlider** [comment]
This is indeed account related. I do not receive any Steam error on my end, even when spamming requests.  
Steam might be just refusing to answer the request for your specific IP. The "Cannot reach steam API" message appears when no answer is received when contacting the steam services. Even authentication fails. Either Steam is down, either your internet is down, either steam (or your firewall) refuses the connexion between the app and steam servers.
I'd advise going through mods one by one to avoid API spamming.
