### ISSUE TITLE
[BUG] 'admins[]=' array in 'config.cfg' empty unless you go to 'performance + scripting' tab after opening FASTER.

### ISSUE THREAD

**Issue by Drift91** [Foxlider/Fox-s-Arma-Server-Tool-Extended-Rewrite#24]
**Describe the bug**
If you launch a server profile *without* going to the 'performance + scripting' tab since launching FASTER the 'admins[]=' array in '<server name>_config.cfg' will remain empty even if you've entered SteamIDs into the 'Admin IDs' field of the 'performance + scripting' tab of the server profile.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'performance + scripting' tab of a server profile.
2. Enter any SteamID(s) into 'Admin IDs' field.
3. Save profile and completely close out of FASTER.
4. Launch FASTER and go to the previously mentioned server profile.
5. Do *not* open any tabs other than the already opened 'Settings' tab.
6. Click the 'Launch' button.
7. Check the '<server_name>_config.cfg'

**Expected behaviour**
'admins[]=' array should be populated.

**Actual behaviour**
```SQF
admins[]= {
};
```

**Screenshots**
N/A

**OS Version (required):**
 - OS: Windows Server 2016 (1607)
 - Version 1.2d

**Additional context**
Possibly related to #14. However it's my understanding that #14 was fixed in 1.2c.

**Edit:**
While reproducing #25 I discovered a similar thing happens with the 'missions' class and 'Missions + Client' tab if using a custom 'missions' class.

**Comment by Foxlider** [comment]
Fixed in 1.2e
