### ISSUE TITLE
[BUG] Backslashes erroronously added to beginning of mission names in 'missions + client' tab and missions class.

### ISSUE THREAD

**Issue by Drift91** [Foxlider/Fox-s-Arma-Server-Tool-Extended-Rewrite#25]
**Describe the bug**
When using the 'Missions' field of the 'Missions + Client' field the mission classes have a blackslash (\) appended to the beginning. This also occurs in the FASTER 'user.config' and the 'Missions' class of 'config.cfg'.

**To Reproduce**
Steps to reproduce the behaviour:
1. Select mission in 'Missions' field.
2. Launch the server.
3. Check the above mentioned config files.

**Expected behaviour**
No backslash in the mission name.

**Actual behaviour**
Check screenshot below.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/2638764/62643417-ee00ea80-b915-11e9-906a-4ff818db6c01.png)

**OS Version (required):**
 - OS: Windows Server 2016 (1607)
 - Version 1.2d

**Additional context**
N/A

**Comment by Foxlider** [comment]
Fixed in 1.2e
