### ISSUE TITLE
[BUG] Profile list

### ISSUE THREAD

**Issue by N0FG** [Foxlider/Fox-s-Arma-Server-Tool-Extended-Rewrite#26]
**Describe the bug**
The profile list spills out of it's designated area

**To Reproduce**
Steps to reproduce the behaviour:
Create more than 9 server profiles

**Expected behaviour**
More than 9 profiles should stay within the boundaries of the profile box and the arrows keys are needed to see them

**Actual behaviour**
The list keeps creating new profiles outside the boundaries of the box.

**Screenshots**
![image](https://user-images.githubusercontent.com/48415651/63314402-ccd1ce00-c307-11e9-8d6a-463e94de3796.png)

**OS Version (required):**
 - OS: [Windows 10
 - Version 1803

**Additional context**
Ideally a new feature for a scroll bar in the window at the side when more than 9 server profiles are created is required for quick and easy access to server profiles (The same as the mods windows have)

![image](https://user-images.githubusercontent.com/48415651/63306315-4f4b9500-c2ea-11e9-95ee-b8aecff88bd6.png)

**Comment by Foxlider** [comment]
Oh wow. Did not think about this. Will fix it.

**Comment by Foxlider** [comment]
![image](https://user-images.githubusercontent.com/19773387/63349519-e7359700-c35b-11e9-843c-c6c3b779f9f6.png)
Watcha think ?

**Comment by N0FG** [comment]
Also perfect...Cheers for the effort and work.
