### ISSUE TITLE
[FEATURE] Extra config params

### ISSUE THREAD

**Issue by N0FG** [Foxlider/Fox-s-Arma-Server-Tool-Extended-Rewrite#27]
**Is your feature request related to a problem? Please describe.**
Can't add additional server config params such as lobbyIdleTimeout, autoSelectMission, drawingInMap, forceRotorLibSimulation etc

**Describe the solution you'd like**
The ability to enter extra server config params via the app.

**Describe alternatives you've considered**
TADST allows the abilty to "Launch as is" which is in itself possibly a good feature to also have as it allows the server to be launched without any changes to the config being made by the app. This means extra params can be manually entered to the config file without the app deleting them on boot up which it does now. 

However, an additional window built  into the app where extra params can be entered that will then get added to the config file by the app and will be incorporated into the save function is what I think would be the best solution if possible. (Similar to  message of the day window)

![image](https://user-images.githubusercontent.com/48415651/63306452-e0227080-c2ea-11e9-9561-06dbbb3442e4.png)

**Comment by Foxlider** [comment]
Is adding settings a thing ? 🤔 
This is an interesting thing to add indeed.

**Comment by N0FG** [comment]
The default setting of the app creates this list of params in the server config and most of the values can be changed with the app.

![image](https://user-images.githubusercontent.com/48415651/63342326-75ede800-c34b-11e9-8fbd-2462d524bf5e.png)

Some options in the app add new params to the config:

headlessClients[] = {"127.0.0.1"};
localClient[] = {"127.0.0.1"};
loopback = 1;
disconnectTimeout = 90;
maxdesync = 0;
maxping = 60;
maxpacketloss = 0;
kickClientsOnSlowNetwork[] = { 0, 0, 0, 0 };
logFile = "server_console.log";

But this list of params can't be added to the server because they aren't in the app, or they get deleted, or the information inside the brackets gets deleted on boot up when manually added like the first 3:

allowedVoteCmds[] = { {"kick", false, false, 0.75} };
allowedVotedAdminCmds[] = { {"mission", true, true} };
admins[] = {"<UID>"};

callExtReportLimit = 1000.0;
kickTimeout[] = { {0, -1},{1, 180},{2, 180},{3, 180} };
votingTimeOut[] = {60, 90};
briefingTimeOut[] = {60, 90};
lobbyIdleTimeout = 300;
missionsToServerRestart = 8;
missionsToShutdown = 8;
autoSelectMission = true;
randomMissionOrder = true;
disableChannels[] = { {0,false,true} };
drawingInMap = false;
skipLobby = false;
forceRotorLibSimulation = 0;
missionWhitelist[] = {"intro.altis"};

Obviously they don;t all get used, but there's a few are definitely useful "randomMissionOrder" and I had to add a script to a mission to prevent "drawinginmap" when apparently it should have been possible in the config.

**Comment by Foxlider** [comment]
Oh ok... Will do, then

**Comment by Foxlider** [comment]
Thing is the UI is quite tricky to work with... Everything is tightly set up so if I move something it will either ruin everything around or crash the app... Let's hope it does not cause too much trouble.

**Comment by N0FG** [comment]
Yeah lol I don't doubt it. Maybe reduce the size of the message of the day window and add a scroll bar to it, or even the admins ID list window would be better. Otherwise just adding the "Launch as is" ability like TADST has is a less eloquent solution that still works and only needs a tick box and name...
![image](https://user-images.githubusercontent.com/48415651/63345771-c79a7080-c353-11e9-893c-b7221a3a2455.png)

**Comment by N0FG** [comment]
If only it was as simple as using photoshop says you....

![image](https://user-images.githubusercontent.com/48415651/63349273-56f75200-c35b-11e9-819d-b4f9d47adbfd.png)

**Comment by Foxlider** [comment]
![image](https://user-images.githubusercontent.com/19773387/63349449-bce3d980-c35b-11e9-81e1-12f3beb6dfe2.png)
The performance + Scripting window is already quite big. Made some room.

**Comment by N0FG** [comment]
Perfect!

**Comment by Foxlider** [comment]
Also fixed #26
