### ISSUE TITLE
MOD List not appearing

### ISSUE THREAD

**Issue by eric963** [Foxlider/Fox-s-Arma-Server-Tool-Extended-Rewrite#29]
Release v20190820.1

After starting FASTER and clicking on the "STEAM MODS" the MOD window does not populate with your current installed mods.

After you check for updates the mods will then appear in the mod window area.  It will continue to display the MODS until you exit.  The next time you start FASTER it will do the same thing, no MODS showing up in the window

**Comment by Foxlider** [comment]
This issue appears only when "auto ckeck for mod updates" is not on. 
Fixed in 1.2f
