### ISSUE TITLE
[BUG] Headless client failing to connect

### ISSUE THREAD

**Issue by N0FG** [Foxlider/Fox-s-Arma-Server-Tool-Extended-Rewrite#32]
**Describe the bug**
When booting a headless client with the server it fails to connect

**To Reproduce**
Steps to reproduce the behaviour:
1. Set up server with headless client and correct mods enabled
2. Start server
3. See error in dedicated client window and disconnect message in dedicated host window.

**Expected behaviour**
Server starts and headless client successfully connects to it

**Actual behaviour**
Server starts and headless client starts but doesn't successfully connect to server.

**Screenshots**
![image](https://user-images.githubusercontent.com/48415651/63644550-d1252f00-c6eb-11e9-8893-dd335c36fb94.png)
![image](https://user-images.githubusercontent.com/48415651/63644556-f74acf00-c6eb-11e9-9a14-60dd803ff295.png)

**OS Version (required):**
 - OS: . Windows 10 
 - Version1803

**Additional context**
Doing the exact same set up in FAST2 the headless client connects without any problem. In FASTER it's kind of like it's not enabling the mods correctly for the HC. The actual server runs fine and I'm able to connect ok with normal client. Reported on the FAST discord by another user and checked by me on last version and latest update of FASTER, same result on both versions.

RPTs  dm'd in FASTER discord.

**Comment by Foxlider** [comment]
Will be fixed in next update

**Comment by Foxlider** [comment]
Issue : Old code was used to get the checked mods. Fixed a long time ago for ArmaServer but not for the headless client. Fixed.
