### ISSUE TITLE
[FEATURE] Arma3LegacyPorts branch

### ISSUE THREAD

**Issue by alexbobp** [Foxlider/Fox-s-Arma-Server-Tool-Extended-Rewrite#33]
Bohemia Interactive sadly does not pay to keep their linux port up to date, so my linux-using friends cannot play on most ArmA 3 servers, which are kept up to date.

I'd love it if this tool had support for downloading the legacy port compatible version of ArmA 3 in order to host a server for linux users.  The beta code on steam for this branch is Arma3LegacyPorts.

**Comment by Foxlider** [comment]
This is an interesting request. Though I have no way of testing it... 
I will try to add every branch of arma server but that might take some time.

**Comment by Foxlider** [comment]
NOTES FOR SELF : 
Test every server branch if it works
https://community.bistudio.com/wiki/Arma_3_Steam_Branches

**Comment by Foxlider** [comment]
Being worked on
