### ISSUE TITLE
[FEATURE] Allow steamcmd to use cached credentials

### ISSUE THREAD

**Issue by alexbobp** [Foxlider/Fox-s-Arma-Server-Tool-Extended-Rewrite#34]
Every time I do pretty much anything in FASTER that invokes steamcmd, the tool initiates a fresh login and throws me a steam guard prompt (actually 2 in a row, no idea why).  It gets really annoying having to fish my phone out for every little step.

However, if I manually run steamcmd and issue the command "login username" with no password, it logs me right in immediately.  In my experience (administrating various steamcmd based servers in the past), steam will generally keep these cached credentials valid for days at a time between full logins.  If I understand correctly, the catch is that to use cached credentials, you have to attempt a login with only the username and no password, and issuing login with username and password will always re-authenticate from scratch.

Please make the tool attempt a login with just username first, and then re-issue the attempt using username and password only if the first attempt fails.  This will save steam guard users lots of time and effort.

Note that this does not add any additional security risk.  steamcmd is *already* caching valid login tokens by default, as the service allows, and users can already use those tokens whenever they manually run steamcmd and login without providing a password.  If a user wants the security of *not* caching an authed login, they will have to adjust steamcmd accordingly (I don't know the details on how to do that).

**Comment by Foxlider** [comment]
That's the point... Steamcmd SHOULD already cache logins and the user should not be prompted to login every goddamn time. I'm working on it though.

**Comment by Foxlider** [comment]
Until a new way of communicating with SteamCMD is found, this will be impossible.

Only workaround so far is to login by using steamcmd manually.

**Comment by Foxlider** [comment]
As I thought... 

> 
> 
> The issue is that SteamCMD often isn't writing to standard output - under Windows it's writing data directly to the console buffer without using the standard IO streams. This means that in order to capture it's output programmatically you have to do some voodoo black magic with the Win32 console API.
> 
> It also outputs the results of things like +app_info_print in one _huge_ write instead of a line at a time, which requires that you have to force the console to have a massive vertical buffer to capture all the output or you'll just end up with the last screen buffers worth of output.
> 
> It's the kind of thing I'd do if I were _deliberately_ trying to prevent someone from reading the output programmatically while still being able to read it when executed by hand on a console. I have managed to work around it but it was a significant amount of work.
> 
> [...]
> 
> We had to produce a complex console application that can create and manipulate a virtual console buffer (without an actual console window attached) that it then makes the 'misbehaving' application use, and then it scans the virtual console row by row to get the data and write it to standard output so other applications can read it normally. It's really really messy and uber-hacky but it works just barely well enough to get data out.

I'll still have to try out some things...

**Comment by Foxlider** [comment]
Closed until Steam fixes their steamcmd
