### ISSUE TITLE
Non stop gun

### ISSUE THREAD

**Issue by N0FG** [Foxlider/Fox-s-Arma-Server-Tool-Extended-Rewrite#35]
**Describe the bug*
Non stop firing and sound animation for guns

**To Reproduce**
Steps to reproduce the behaviour:
1. Boot the server
2. Join mission
3. Choose weapon and fire
4. Observer sees and hears bug (Player firing the weapon sees and hears normal)

**Expected behaviour**
Normal weapon behaviour seen and heard by observer

**Actual behaviour**
Continuous firing animation and sound for observer

**Screenshots**
https://www.youtube.com/watch?v=bjpU2V75GEc&feature=youtu.be
Same bug different server (using FAST2 I believe) Restarting the server fixed it for this guy, but that didn't work when I tried it.

**OS Version (required):**
 - OS: [e.g. Windows 10 1903]
 - Version [e.g. 1.1a]

**Additional context**
The bug is common to both FASTER and FAST2, but not actually a common bug. I've only witnessed the bug on Voodoo's server and in the youtube video linked. It doesn't happen when the server is booted with TADST from the same Arma folder. Both steam, Arma and FASTER were reinstalled and no extra mods were running. Same result on alternative working and tested mission pbo. I've dropped my client rpt and the servers rpt into a dm on discord. Voodoo can provide OS version for server used, his client rpt and first hand video of bug if needed.

**Comment by Foxlider** [comment]
Weirdest bug. Maybe a badly installed mod ? Maybe missing DLC ?
If you have the RPT with FASTER and the RPT with TADST I'd like to see if there is any difference.

**Comment by Draern** [comment]
I thinks someone mentioned on Flax's discord that it had something to do with a typo in the Basic.cfg file.
I can confirm I stopped using FAST2 because of this.

![image](https://user-images.githubusercontent.com/43252526/65615860-5422f900-dfba-11e9-8386-5c0a643ddf99.png)

**Comment by Foxlider** [comment]
Oooooooooooooooh ok ! I'll check this out then.
