### ISSUE TITLE
[BUG] "allowedVoteCmds" and "allowedVotedAdminCmds" added to config when voting enabled, instead of disabled

### ISSUE THREAD

**Issue by Drift91** [Foxlider/Fox-s-Arma-Server-Tool-Extended-Rewrite#37]
**Describe the bug**
When voting is enabled, instead of when disabled, the following is added to the config:
```
allowedVoteCmds[] = {};
allowedVotedAdminCmds[] = {};
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Disable voting in your server profile
2. Save and launch the profile
3. Check the server.cfg

**Expected behaviour**
The lines should be added when voting is disabled and not added when it's enabled.

**Actual behaviour**
The lines are only added when voting is enabled.

**Screenshots**
N/A

**OS Version (required):**
 - OS: Windows Server 2019
 - Version 1.2f

**Additional context**
N/A

**Comment by Foxlider** [comment]
Interesting... This toggle button  is set up to DISABLE voting when checked even though it was named VotingEnabled.
