### ISSUE TITLE
[BUG] Importing Steam mods from launcher profile does nothing

### ISSUE THREAD

**Issue by Drift91** [Foxlider/Fox-s-Arma-Server-Tool-Extended-Rewrite#38]
**Describe the bug**
When importing Steam mods from a launcher preset the mods don't actually get added.

**To Reproduce**
Steps to reproduce the behaviour:
1. Make a Steam mod preset via the Arma 3 Launcher that contains mods that aren't already in the launcher.
2. Go to the steam mods section.
3. Attempt to import the mods via the "import from Arma 3 launcher profile" button.

**Expected behaviour**
All the mods in the preset/profile should show up in the list of mods in the launcher.

**Actual behaviour**
Nothing occurs.

**Screenshots**
N/A

**OS Version (required):**
 - OS: Windows Server 2019
 - Version 1.2f

**Additional context**
N/A

**Comment by Foxlider** [comment]
Have you tried refreshing the list ? Closing and repoening ? 
It might just be an UI update issue

**Comment by Foxlider** [comment]
Fixed in next update
