### ISSUE TITLE
[BUG] FASTER window too large to fit on low resolution display/RDC Window

### ISSUE THREAD

**Issue by Drift91** [Foxlider/Fox-s-Arma-Server-Tool-Extended-Rewrite#39]
**Describe the bug**
With the new 1.2f version the window no longer fits on my 1024x768 Remote Desktop Connection window, nor the old display hooked up to my server box.

**To Reproduce**
Steps to reproduce the behaviour:
1. Set the desktop resolution to 1024x768 or lower.

**Expected behaviour**
Window should be resizeable, or at least fit in a 1024x768 desktop.

**Actual behaviour**
Critical elements of the window aren't visible without constantly shifting the window around on the screen.

**Screenshots**
![XCq5tDO 1](https://user-images.githubusercontent.com/2638764/65387600-ed31e580-dd16-11e9-8f93-4da788084666.png)

**OS Version (required):**
 - OS: Windows Server 2019
 - Version 1.2f

**Additional context**
I know that 1024x768 is a rather dated resolution and 1920x1080 is basically today's standard. However Windows seems to consider 1024x768 the bare minimum and will only give a warning about sizes smaller than this. Although a very small minority, some people still use old CRT monitors or older LCD displays that can't go above this resolution.

**Comment by Foxlider** [comment]
Hmmm... Indeed this is a problem.

**Comment by Foxlider** [comment]
Fixed in next update
