### ISSUE TITLE
[FEATURE] Add difficulty flags for tactical ping on map and scoreboard

### ISSUE THREAD

**Issue by alexbobp** [Foxlider/Fox-s-Arma-Server-Tool-Extended-Rewrite#40]
The difficulty flags for tactical ping on map and scoreboard are missing.

The config variables are named:
mapContentPing
scoreTable

Thanks for your hard work maintaining this tool! <3

**Comment by Foxlider** [comment]
For now, you can use the additionnal parameters
I'll work on it after some more research
![image](https://user-images.githubusercontent.com/19773387/65584920-ea86f880-df81-11e9-9423-8b6d93cd1828.png)

**Comment by alexbobp** [comment]
Custom difficulty settings normally go in their own file in the user profile folder.  I tried putting them in this box, but it didn't work for me.  If there's a way to make it work, I am missing something.

**Comment by alexbobp** [comment]
update: if I manually add these flags to the .Arma3Profile file, the tool overwrites them upon launching the server

**Comment by Foxlider** [comment]
The scoreTable is fixed. But I'll have to fix the Tactical ping in 1.3e

**Comment by Foxlider** [comment]
Not relevant anymore with the new interface coming
