### ISSUE TITLE
[FEATURE] Ability to boot FASTER as a headless client.

### ISSUE THREAD

**Issue by N0FG** [Foxlider/Fox-s-Arma-Server-Tool-Extended-Rewrite#44]
**Is your feature request related to a problem? Please describe.**
Some missions lock out the ability for mission param changes to be made when headless client boots at the same time as the server.

**Describe the solution you'd like**
The ability to boot FASTER as an independent headless client

**Describe alternatives you've considered**
A timed delay between server boot and client boot as this gives time for the admin to access the mission param settings. Though this is slightly clumsy and still doesn't stop the params getting locked out if the admin gets distracted.

**Comment by Foxlider** [comment]
Maybe add a button to start up HCs separately ? Might fail to log in if the server is still offline though.

**Comment by N0FG** [comment]
Yeah as it should and would do with a normal HC bat file. Can't log into something that isn't there. A  button to start separately would do fine.
