### ISSUE TITLE
[BUG] Saved values wrong after loading saved settings @Server Perfomance

### ISSUE THREAD

**Issue by marc71** [Foxlider/Fox-s-Arma-Server-Tool-Extended-Rewrite#50]
Server Perfomance Settings "Min Error to Send" and "Min Error To Send Near" are wrong after restart - seems to be a localization issue  (German OS Windows Server 2012R2)
**To Reproduce**
Steps to reproduce the behaviour:
1. Have a german os
2. Go to Server Performance
3. Input values 0.002 and 0.02 into "Min Error" fields
4. Save & close FASTER
5. Start FASTER

**Expected behaviour**
Values should be 0.002 and 0.02

**Actual behaviour**
Values are 2 in both fields - which leads to unacceptable server performance... 

**Screenshots**
![input_perfomance](https://user-images.githubusercontent.com/725722/67145494-4a6f7700-f282-11e9-85d9-1cac0455bd2a.jpg)

![settings_after_reloading](https://user-images.githubusercontent.com/725722/67145507-58bd9300-f282-11e9-8ebc-798da981c6b1.JPG)

**OS Version:**
 - OS: Windows Server 2012 R2 Build 9600
 - Version 6.3

Thanks in advance - and thanks for the nice app!!!

**Comment by Foxlider** [comment]
oh wow... that's not good
Are you using the last version ?

**Comment by marc71** [comment]
1.4a is running

**Comment by Foxlider** [comment]
Ok, I'll work on this

**Comment by marc71** [comment]
thanks mate!
