### ISSUE TITLE
[BUG] Server files

### ISSUE THREAD

**Issue by fire-391** [Foxlider/Fox-s-Arma-Server-Tool-Extended-Rewrite#52]
Open file buttons in the logging section don't open the file. Also it seems the server console and mpstatistics files are swapped.

![Capture](https://user-images.githubusercontent.com/36144022/67221369-53368900-f3f9-11e9-922c-d28b816ca2a7.PNG)

 - OS: Windows Server 2016 Standard
 - Version 1.4a

**Comment by Foxlider** [comment]
Could you provide me with the correct files and their locations ? 
I'm working with a PC without arma (with a fake arma in fact) and thus cannot really check those files

**Comment by fire-391** [comment]
The files were stored at steamcmd\arma_main\Servers\*server_name*

**Comment by Foxlider** [comment]
Do you get any error message of does it open the wrong logfile ?

**Comment by fire-391** [comment]
faster does not open any files when clicking the "open" buttons under the settings tab and gives no errors.

**Comment by Foxlider** [comment]
Ok, I'll look into it

**Comment by Foxlider** [comment]
Not relevant anymore with the new interface coming
