### ISSUE TITLE
[BUG] Additional Parameters not saving

### ISSUE THREAD

**Issue by fire-391** [Foxlider/Fox-s-Arma-Server-Tool-Extended-Rewrite#53]
Additional parameters box doesn't save data after closing and reopening FASTER.

Steps to reproduce the behaviour:
1. Go to Performance + Scripting
2. Type something in the additional parameters and click add parameters to config
3. Save profile 
4. Close FASTER
5. Open FASTER
6. See missing code

Saving profile should save parameters

**OS Version (required):**
 - OS: Windows Server 2016
 - Version 1.4a

**Comment by N0FG** [comment]
It seems to add the code on server boot if the box add params to config is checked. but not on instance save.
