### ISSUE TITLE
[FEATURE] Hide button on server-only mods

### ISSUE THREAD

**Issue by fire-391** [Foxlider/Fox-s-Arma-Server-Tool-Extended-Rewrite#54]
The ability to hide certain mods from the Server only list so users can hide non server-only mods that will never be checked in that box.

**Comment by Foxlider** [comment]
what ?

**Comment by fire-391** [comment]
Being able to visually hide mods from the server only list?

**Comment by Foxlider** [comment]
I don't think I should add this unless more people want int to be added.
