### ISSUE TITLE
[BUG] Deleting Local Mod Path (in Windows) Causes Crash 

### ISSUE THREAD

**Issue by Ansible2** [Foxlider/Fox-s-Arma-Server-Tool-Extended-Rewrite#55]
**Describe the bug**
If a path defined for Faster to search for local mods is deleted in Windows and it is not removed from Faster's listing prior to doing so, it will cause the application to crash on start up (appears in processes but never shows the UI) and to crash when selecting a server (if the path was deleted in Windows and not removed from the listing before FASTER was shutdown).

**To Reproduce**
**NOTE:** If FASTER will not launch use `ctrl+z` in Windows Explorer or create another folder with the same path (name) as in step 1.

Steps to reproduce the behaviour:
1. Launch Windows Explorer and create a new empty folder at the path of your choosing.
2. Launch FASTER.
3. If no server profiles exist, create one.
4. In FASTER, go to Settings and add the path of the folder created in step 1 to the searched folders listing.
5. In Windows Explorer, delete the folder created in step 1.
6. Close and relaunch FASTER.
7. Repeat step 5.
8. In FASTER select any server profile.

**Expected behaviour**
- FASTER will launch during step 5.
- FASTER will not crash after completing step 8.

**Actual behaviour**
- FASTER will not relaunch during step 5 unless the **NOTE** is followed.
- FASTER will crash after completing step 8.

**OS Version (required):**
 - OS: Windows 10 Pro 1809
 - Version 17763.805

**Additional context**
Event files from reproduction steps:
[FASTER Event files.zip](https://github.com/Foxlider/Fox-s-Arma-Server-Tool-Extended-Rewrite/files/3832412/FASTER.Event.files.zip)

**Comment by Foxlider** [comment]
Fixed in next version 1.4c
