### ISSUE TITLE
Checkbox for Auto check for updates not saving

### ISSUE THREAD

**Issue by eric963** [Foxlider/Fox-s-Arma-Server-Tool-Extended-Rewrite#6]
Unchecking the box, exiting program then restarting program and the checkbox is enabled again.

**Comment by Foxlider** [comment]
### Cause : 
Bad event handling (oops)

### Workaround : 
You can edit the value in the setting file 
%localappdata%/FoxliCorp/FASTER_xxxxxxxxxxxxxx/x.x.xx.x/user.config
```
<setting name="checkForModUpdates" serializeAs="String">
     <value>False</value>
</setting>
```
