### ISSUE TITLE
Can't get the normal "missions" list to load

### ISSUE THREAD

**Issue by swebow** [Foxlider/Fox-s-Arma-Server-Tool-Extended-Rewrite#62]
Sorry for odd edits, pressed Enter by mistake.

I can't get the normal "missions"/"maps" list open when I use FASTER to host the server. It works if I only pick 1 mission and it only runs that mission. Then it's fine. But it would be lovely if we could get the option to pick between all missions thats in the MP folder list or atleast all you click on in FASTER.

**Comment by Foxlider** [comment]
FASTER acts like a mod loader for Arma. This might be an Arma limitation.
