### ISSUE TITLE
Could not reach Steam API

### ISSUE THREAD

**Issue by CySpiegel** [Foxlider/Fox-s-Arma-Server-Tool-Extended-Rewrite#69]
This error occurs every time i try to add a mod from workshop.

Could not reach Steam API : 
[WebException] The remote server returned an error: (401) Unauthorized.

   at System.Net.HttpWebRequest.GetResponse()
   at FASTER.Models.SteamWebApi.ApiCall(String uri)

**Comment by Foxlider** [comment]
Have you checked your login informations ? What mod are you downloading ?

**Comment by CySpiegel** [comment]
login information is correct
and was trying to add cba to the server
none of the mods from workshop will get added to faster
i even tried to import mod presets

**Comment by Falcon911** [comment]
1.5c fixed this.
