### ISSUE TITLE
[BUG] Can't disable mission voting

### ISSUE THREAD

**Issue by warlocc** [Foxlider/Fox-s-Arma-Server-Tool-Extended-Rewrite#78]
I've set the server to no voting, and defined a custom mission class. I've enabled Persistent Battlefield and Auto Init.

Despite setting this up, when the server launches, it launches into the vote menu, and requires voting by players to actually launch the mission.

Windows 10
FASTER version 1.5c

![a3e702cf2bd0fcc0b9868c88655fc778](https://user-images.githubusercontent.com/41884701/72660004-ac30a180-3995-11ea-8f7f-f2c9c57f5f5f.png)

![d5e950754dda48d2f90a09dc04e8290f](https://user-images.githubusercontent.com/41884701/72660008-b9e62700-3995-11ea-95cd-3f501f42038f.png)

**Comment by Foxlider** [comment]
Fixed in 1.7a
