### ISSUE TITLE
[BUG] When creating a server profile with the new tool, the profile doesn't build right

### ISSUE THREAD

**Issue by armyinf0703** [Foxlider/Fox-s-Arma-Server-Tool-Extended-Rewrite#8]
**Describe the bug**
I set up a server and set up a custom difficulty, here is the profile it built. When I hit launch server, server would not start would would get a errors saying the profile is busted 

**Screenshots**
Fox FAST Tool Profile
https://i.gyazo.com/eb67f5fcf9c9a00ffac97aff92b37a68.png

TADST Profile
https://i.gyazo.com/5853bd034046ed5f71477b84d9ca47e5.png

**Comment by Foxlider** [comment]
I see the issue. Again, it seems my configuration is not parsed correctly
