### ISSUE TITLE
Mod HTML giving unable to install mod

### ISSUE THREAD

**Issue by Xyonfire** [Foxlider/Fox-s-Arma-Server-Tool-Extended-Rewrite#80]
**Describe the bug**
The Faster tool tells me it cant install a mod and gives link but installed the same mod 1 week ago

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to steam mods
2. Click on import HMTL
3. Import HTML

**Expected behaviour**
The mods to install

**Actual behaviour**
Says cant install mod and when removing said mod gives another mod and does this till the HTML is empty 

**Screenshots**

**OS Version (required):**
 - OS: Windows Server 2012 R2 standard
 - Version N/A

**Comment by SirGhosty22** [comment]
Can you send the html that was causing issues?

**Comment by Xyonfire** [comment]
i can well its two but yeah

**Comment by Xyonfire** [comment]
Github is refusing to let me upload it

**Comment by Xyonfire** [comment]
![75ccaca29a2ef187734b5fd46dd0b96c](https://user-images.githubusercontent.com/44716436/73502978-5a721900-4390-11ea-96c6-c6b2ea458052.png)
![04e69bdf150e7e242f3a129d99436476](https://user-images.githubusercontent.com/44716436/73502979-5b0aaf80-4390-11ea-92c6-b30ad4388959.png)
![5f18f82b0a6c596097bc2535683472e7](https://user-images.githubusercontent.com/44716436/73502980-5b0aaf80-4390-11ea-8bdc-4b5e039ac9af.png)

**Comment by warlocc** [comment]
Same happened to my modpack of 16 mods. Adding them one at a time, manually, works as expected.

**Comment by SirGhosty22** [comment]
Try uploading the html to dropbox/googledrive or alternatively https://send.firefox.com/
Can you also check event viewer for any errors faster related?

**Comment by Xyonfire** [comment]
there was no error just said unable to import mod and then gave me the link

**Comment by SirGhosty22** [comment]
What link did it give you?

**Comment by warlocc** [comment]
The error message says "Unable to import mod" and then links the mod it's unable to import- which, by process of elimination, is all of them.

**Comment by Foxlider** [comment]
Three things : 
Check your version of FASTER. A mod import issue was fixed in 1.5d
Check your event viewer : details might be available there about the error
Steam was down yesterday from 2pm to 21pm

**Comment by Foxlider** [comment]
No answer after more than a month. Closing issue.
