### ISSUE TITLE
[BUG] FASTER won't launch. Metro Icon Packs?

### ISSUE THREAD

**Issue by guttplutt** [Foxlider/Fox-s-Arma-Server-Tool-Extended-Rewrite#82]
**Describe the bug**
FASTER doesn't launch. Even viewer mentions problems with icons and .NET core (see additional)

**To Reproduce**
Steps to reproduce the behaviour:
1. Start FASTER

**Expected behaviour**
After pressing Yes on the UAC screen FASTER should launch

**Actual behaviour**
Nothing happens

**Screenshots**

**OS Version (required):**
 - OS: Windows 10 Home
 - Version 10.0.18363 Build 18363

**Additional context**
Information taken from Windows Even Viewer

Description: A .NET Core application failed.
Application: FASTER.exe
Path: E:\FASTER.exe
Message: Error:

  An assembly specified in the application dependencies manifest (FASTER.deps.json) was not found:
    package: 'MahApps.Metro.IconPacks', version: '3.2.0'
    path: 'lib/netcoreapp3.0/MahApps.Metro.IconPacks.BoxIcons.dll'

[Error FASTER.zip](https://github.com/Foxlider/Fox-s-Arma-Server-Tool-Extended-Rewrite/files/4207945/Error.FASTER.zip)

**Comment by Foxlider** [comment]
This is a known bug and I'm actively working on a fix. 

Some file corruption happens in the folders of FASTER and some libraries go missing. 

Current fix is to delete the FASTER folders in `%localappdata%\Temp.net` and everything should work fine
