### ISSUE TITLE
Unresponsive while downloading workshop item

### ISSUE THREAD

**Issue by MildlyInterested** [Foxlider/Fox-s-Arma-Server-Tool-Extended-Rewrite#83]
**Describe the bug**
While downloading workshop item FASTER doesn't respond to any user inputs like clicking. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Start to download large mod
2. Try accessing Server Profiles or sth else
3. FASTER not responding and continues to show Steam CMD Output

**Expected behaviour**
Be able to edit profiles etc.

**Actual behaviour**
A clear and concise description of what actually happened.

**Screenshots**

**OS Version (required):**
 - OS: Windows Server 2016
 - Version 1.6a

**Comment by Foxlider** [comment]
Not a bug. The navigation is disabled while steamCMD is called to avoid any bugs while SteamCMD is running.
