### ISSUE TITLE
Mission difficulty is not carrying over when new mission is selected.

### ISSUE THREAD

**Issue by Stevo-OLY** [Foxlider/Fox-s-Arma-Server-Tool-Extended-Rewrite#84]
When a mission is loaded on start up it loads with the correct difficulty settings, when the mission is switched to another mission through #missions it does not carry over the difficulty settings, the new mission/s when loaded defaults to the standard settings with 3rd person view, crosshair etc which have been disabled in the difficulty settings on the profile.

**To Reproduce**
Steps to reproduce the behaviour:
1. Select 2 missions on the F.A.S.T.E.R. launcher and set up the difficulty settings.
2. Save the profile on the launcher.
3. Launch the Arma 3 server.
4. Join the server the first mission loads and load into the mission.
5. Check that the difficulty settings are working. (they always do on the first mission)
6. Login to Admin using #login and change the mission to the second mission using # missions.
7. Load into the new mission and check the difficulty settings.
8. New mission has default settings with 3rd person, crosshair etc turned back on.

**Expected behaviour**
Change the mission using # missions and the difficulty settings carry over to the other mission/s.

**Actual behaviour**
Change the mission using # missions and the difficulty settings do not carry over to the other mission/s they change to the default settings.

**OS Version (required):**
 - OS: Windows Server 2019 Standard
 - i5 - 6500 3.2 GHz
- 16GB RAM

**Comment by N0FG** [comment]
When you select the new mission, you also have to choose "custom" difficulty from the list on the left.

**Comment by Stevo-OLY** [comment]
Difficulty preset for all the missions are set to custom on the launcher, it is when I switch them in game through # missions the settings do not carry over to the new mission when changed in-game through Admin commands.
