### ISSUE TITLE
[BUG] FASTER no longer starts

### ISSUE THREAD

**Issue by Pinecone227** [Foxlider/Fox-s-Arma-Server-Tool-Extended-Rewrite#96]
**Describe the bug**
I don't know what happened, I restarted the machine and after loading the OS again, FASTER won't start again.

**To Reproduce**
Steps to reproduce the behaviour:
1. Attempt to start FASTER
2. Nothing happens after confirming UAC prompt.

**Expected behaviour**
FASTER should start
**Actual behaviour**
FASTER does not start, not present in task manager or anywhere

**OS Version (required):**
 - OS: [Windows 10 1909]

**Comment by Garrus167** [comment]
The funny thing is that I am having this same issue. The only difference is that I am running it on Windows Server 2019. It is doing the same thing as well.

**Comment by Foxlider** [comment]
This is a known issue. The reason might be that the app crashes before launching.
In the discord's FAQ channel : 
![image](https://user-images.githubusercontent.com/19773387/85197347-b3f7c780-b2e0-11ea-92ca-9278c8fef058.png)

**Comment by Foxlider** [comment]
No answer after 20 days. Closing issue
